# Generated by Django 4.2 on 2024-05-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id_telegram',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='id пользователя в телеграм'),
        ),
    ]
